### ISSUE TITLE
No app build

### ISSUE THREAD

**Issue by marcoaccardi** [alexrodi/Phi#11]
**Describe the bug**
I can't run the app.

**Screenshots**
<img width="724" alt="Screenshot 2020-04-11 at 17 49 45" src="https://user-images.githubusercontent.com/51090929/79048466-80802900-7c1d-11ea-9ced-f94b57e904ba.png">

**Desktop (please complete the following information):**
 - MacOs: 10.14.5
 - XCode 11.2

**Comment by alexrodi** [comment]
@marcoaccardi Which version of Juce do you have?

**Comment by marcoaccardi** [comment]
I've open it with Projucer version 5.4.7 ( the latest). You should update it :)

**Comment by alexrodi** [comment]
It's the latest now `jucerVersion="5.4.7"`
