### ISSUE TITLE
Fix .travis file in gh-pages branch

### ISSUE THREAD

**Issue by marcoaccardi** [alexrodi/Phi#24]
doxygen documentation files are placed in the main folder -> Phi/docs

**Comment by alexrodi** [comment]
This doesn't seem to be possible, gh-pages is a deployment repo that is not meant to be worked on.
These are the only options:
<img width="307" alt="Screenshot 2020-04-19 at 12 06 23" src="https://user-images.githubusercontent.com/22116071/79685098-512d7580-8236-11ea-857b-8bc915021192.png">

So I guess we have to keep it this way.
